### ISSUE TITLE
Add a clause to the Terms for educators. So they stop emailing asking if they can use it for educating.

### ISSUE THREAD

**Issue by efatsi** [vigetlabs/storyboard#113]
I've gotten 2 emails in the last month from educators asking if Storyboard can be used for educational purposes. One even offered to purchase a license ... a conversation for another day.

Is there some verbiage we could add to the site's [Terms](https://storyboard.viget.com/terms) so educators feel comfortable using the service without reaching out first?

**Comment by efatsi** [comment]
@cindycaldwell do you have any thoughts here?

**Comment by cindycaldwell** [comment]
I've added a sentence to address this issue in this document: https://docs.google.com/document/d/1gaRXq-j639M9VzHiA7cJWYNQ2WfHcGJuNPj920H56Yo/edit#heading=h.ydp1uqmztgg0

I've flagged Andy to review and approve.  Once he does, you can add the new sentence to the Terms page.

**Comment by noahko96** [comment]
This seems to have been done awhile ago and this issue just never got closed, so closing it out now.
