### ISSUE TITLE
Add Google Tag Manager script

### ISSUE THREAD

**Issue by paulmkoch** [vigetlabs/storyboard#151]
Hi @noahko96, welcome to Viget!

We're hoping to add Google Tag Manager to the Storyboard site. Would you be able to add this code to the head of the site this week?

```html
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-NP6STPC');</script>
<!-- End Google Tag Manager -->
```

Thanks!
cc: @Serena-R

**Comment by noahko96** [comment]
Hey Paul,

That code is already in the header of Storyboard. It looks like it was put there on Jun 6, 2019 by Albert Wavering as part of commit 1d037e75 solving issue #52.

**Comment by noahko96** [comment]
Going to close this ticket out. Let me know if there is anything else you need configured to get GTM up and running.

**Comment by paulmkoch** [comment]
🤯   Whoops, sorry about that! I checked to see if a gtm.js file was loading before creating this ticket, but nothing was showing up because no container had been published. Thanks!

**Comment by efatsi** [comment]
@paulmkoch was this ever set up? I logged in using ga@viget.com to GA and saw 0s on the Storyboard project
<img width="1449" alt="Screen Shot 2021-09-07 at 2 11 38 PM" src="https://user-images.githubusercontent.com/1410181/132404996-93dfc7e5-e0b9-4c34-81ad-448fa4750e40.png">

(Noah and I were curious how much traffic coming in was on mobile)

**Comment by paulmkoch** [comment]
@efatsi @noahko96 I just published the tracking, so you should start to see data from today onward.

Serena set up Google Tag Manager, I gave one round of feedback, and she adjusted. I haven't had time to review her changes and hadn't prioritized this after the internship ended. I went ahead and published without reviewing because the stakes are relatively low.
