### ISSUE TITLE
UX enhancements to debugger

### ISSUE THREAD

**Issue by efatsi** [vigetlabs/storyboard#158]
The debugger looks like it's functioning beautifully. Let's take a UX pass at it.

### Background:
- The `Debug` link in the story editor was a fairly useless link for the past year or so. I have a feeling most users grew to just ignore that as an option.

### Idea:
- Remove the `Debug` link (and maybe the correlated debug mode that it kicks you into)
- Instead, recognize when a story owner is playing one of their stories and expose a debug link or icon in the bottom corner. Clicking on that should swing up the debugger UI and functionality.
- I believe this means that public stories will never be debuggable (since no one is technically the owner of it).

_Note: the follow-up ticket to this is to expose a similar(ish) UI for non-admins, so probably worth keeping that in mind as you work through this._

**Comment by noahko96** [comment]
@efatsi Couldn't we just use the same functionality we use for editing for debugging, instead of only allowing the the owner of the story debug it? Like if a user can edit a story, shouldn't they be able to debug it as well. Especially since debugging doesn't actually change the story at all.

**Comment by efatsi** [comment]
Yeah that makes sense to me. Although I'd argue against your last sentence there, since you could use the debugger to modify your stats/items, you could change the flow of a story that used those to alter available story paths.

**Comment by noahko96** [comment]
Ok, I guess I meant you couldn't edit the story's source. Like changing stuff in the debugger doesn't change anything for future users.

**Comment by efatsi** [comment]
Yeah that's correct. I like the idea that if you can edit you can also debug 👍
