### ISSUE TITLE
Where is the story-creater located?

### ISSUE THREAD

**Issue by selcuko** [vigetlabs/storyboard#161]
Hey, great project!
As this is an open-source project, I would like to inspect the story-creator codes - it seems dope. Also, I really couldn't find where did you use React.
Thank you.

**Comment by efatsi** [comment]
Hi @divisia, the story-creator source is owned by the story creators, that part isn't freely available to the public (unless the story creator toggles a setting to expose a link to the source at the end of a story).

Most of the React code is in these two files - https://github.com/vigetlabs/storyboard/blob/main/app/javascript/src/components/Editor.tsx and https://github.com/vigetlabs/storyboard/blob/main/app/javascript/src/components/Player.tsx. We like to have more organized code than this on our client projects but for these side projects we play it a little more fast and loose.
