### ISSUE TITLE
Allow users to upload audio to their scenes.

### ISSUE THREAD

**Issue by noahko96** [vigetlabs/storyboard#164]
Allow a user to upload audio either as a pre-made file or recording it in the app themself to be played during the scene that they attached it to.

**Comment by efatsi** [comment]
One implementation note. When playing the story that has audio on a mobile device, a browser session will not play sound by default unless some sound is first manually triggered by a user click/touch event. Once a user has triggered any sound, then subsequent sounds can be played programmatically at will, but some UX thought might need to go into how that first sound is triggered.
