### ISSUE TITLE
Top content is cut off on short screens 

### ISSUE THREAD

**Issue by efatsi** [vigetlabs/storyboard#49]
Don't even have to be that short. But the shorter it is, the worse the problem gets: 
https://storyboard.viget.com/the-choices-we-make-an-interactive-history-experience

<img width="1250" alt="Screen Shot 2019-05-17 at 3 59 29 PM" src="https://user-images.githubusercontent.com/1410181/57958334-ca9d4500-78bc-11e9-8c33-1953d4124251.png">

**Comment by nhunzaker** [comment]
@efatsi did I fix this?

**Comment by efatsi** [comment]
yessir
