### ISSUE TITLE
Add Terms and Conditions Page

### ISSUE THREAD

**Issue by awavering** [vigetlabs/storyboard#55]
Add a link at the bottom of the marketing site and the web app to a dedicated T&C page.

Final URL: https://storyboard.viget.com/terms

Approved T&C copy: https://docs.google.com/document/d/1gaRXq-j639M9VzHiA7cJWYNQ2WfHcGJuNPj920H56Yo/edit?ts=5d0c037d

**Comment by efatsi** [comment]
Check em: https://storyboard.viget.com/terms

**Comment by awavering** [comment]
Looks good to me! :shipit:
