### ISSUE TITLE
Allow for offline playing

### ISSUE THREAD

**Issue by efatsi** [vigetlabs/storyboard#85]
We heard from a first responder training outfit that they'd love to use this tool but need to be able to play the stories offline. I think the only difficult task is the fact that right now story content is dynamically loaded on page load, and we need it to be loaded with the page for someone to be able to download the whole thing and be good to go.

This used to be how things worked, but we added in the dynamic content loading to get around cacheing issues we were seeing. Can see the updates to [player.tsx here](https://github.com/vigetlabs/storyboard/commit/91e143527a7e6a67fcd12904ad0fa4d43d08ac6c#diff-933fe1fd0c5ef6c6f2f73e020bf32c03).

Would want to be clever about the UI for this, as most users don't care about offline play I'm guessing. Maybe an "offline version" link next to each story in your story index - https://storyboard.viget.com/mine. Which loads a very similar but slightly different player pack that pulls the data from a SEED variable instead of through a fetch. And exposes a "Download for Offline" button which triggers the native browser save page functionality.

**Comment by efatsi** [comment]
QA looks good. Couple thoughts:
- let's see if we can remove the EDIT / SAVE buttons from the offline mode. Probably can remove the EDIT one altogether, and then figure out how to hide the SHOW one when the offline download is in.
- if I save the page while the save instruction modal is open, then the local copy opens with the modal sliding into view. Maybe intercept the cmd-s event and close the modal before the default functionality kicks in?

**Comment by DanielSBrown** [comment]
> * let's see if we can remove the EDIT / SAVE buttons from the offline mode. Probably can remove the EDIT one altogether, and then figure out how to hide the SHOW one when the offline download is in.

By the second sentence, do you mean hiding the button if the user has already downloaded the current page?

**Comment by efatsi** [comment]
Yeah, should maybe be able to switch on the browser's path? detect if it's a local file rendering and display the offline version a little differently.
