### ISSUE TITLE
Allow users to differentiate between finished endings and in progress scenes

### ISSUE THREAD

**Issue by efatsi** [vigetlabs/storyboard#89]
- Add a checkbox to the SceneEditor for users to mark scenes as "completed". Visually, this should probably go in a new "settings" area in the SceneEditor.
- Completed scenes should have a different visual treatment in the main view. Either by choosing different colors for the scenes, or (if possible) add a different class to those scene elements that lets us add whatever visual treatment we want (maybe a little lock icon?)

**Comment by DanielSBrown** [comment]
@efatsi Just to clarify, the different visual treatment is for the player's view? Also, would this different visual treatment be in addition to the "replay" button that's present in final scenes while playing currently?

**Comment by efatsi** [comment]
Nope, this is for the editor view. Here's the user feedback:

> it would be nice to be able to color-code completed endings differently from dead-ends that are still in progress. My game has become so large and complicated that I can't keep track of which red boxes signify dead ends that just aren't finished yet and which signify actual completed endings, and it would be nice to differentiate them without having to click on each red box to see if it's finished or not.

**Comment by DanielSBrown** [comment]
Ahhhh okay. That makes more sense. I was struggling with thinking about how the player would need more guidance that they were finished, and haven't really seen complex stories while in editor mode to understand the use case. The feedback makes this a lot clearer. Thanks!
